# Generated by Django 3.2.4 on 2021-06-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210610_0633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='glavbudgetclass',
            unique_together={('code', 'name')},
        ),
    ]
